app = "igdownloader"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  COOKIES_DIR = "/data/cookies"

[[mounts]]
  source = "cookies"
  destination = "/data"

  [checks]
  [checks.http]
    port = 3000
    path = "/"
    interval = "10s"
    timeout = "5s"
